### ISSUE TITLE
Problem with calculating floating point numbers with PseudoInverse library

### ISSUE THREAD

**Issue by Mitchell-Lee-93** [PX4/PX4-Matrix#148]
Hello,
I had an error while using the pseudo inv library so I want to share the bug.
There were some cases that pseudo inv becomes a null matrix when I use a floating-point number matrix as an input. It was because of the tolerance in fullRankCholesky function. In case of using float, even though L(k,r) is near zero value in floating-point number (ex:5.96e-8), the tolerance might has even smaller value(ex:8.59e-12). If it happens, it makes an error and outputs the null matrix(which makes the output a zero vector).
 
![스크린샷, 2020-08-26 13-44-21](https://user-images.githubusercontent.com/56542570/91256469-5f6e3e00-e7a2-11ea-9fa5-98c2d767f174.png)

To fix this, In my case which only using the floating-number matrix, I made the following change in void fullRankCholeskyTolerance(Type &tol) function 

**_'tol /= 1000000000;'_**  to  _**'tol = 0.000000001f;'**_ 

and added the following code right before 'if (L(k, r) > tol) {' in fullRankCholesky function

_**'if (L(k,r)<0.0000001f) L(k,r)=0.0f;'**_

the result has been changed
from

 ![image](https://user-images.githubusercontent.com/56542570/91256537-8d538280-e7a2-11ea-8a00-cd49a6c111ab.png)

to

![image](https://user-images.githubusercontent.com/56542570/91256547-93496380-e7a2-11ea-85a7-c41f8aa20545.png)

I don't think this is a good solution for the general case but in my case, I guess it works.

Best regards,

Mitchell Lee

**Comment by bresch** [comment]
@Mitchell-Lee-93 is that fixed?

**Comment by Mitchell-Lee-93** [comment]
Instead of the issue, I just made a new pull request! please check the new pull request. I'm sorry for the late response.

**Comment by bresch** [comment]
Ok, cool, thanks. I'm adding the link here: https://github.com/PX4/PX4-Matrix/pull/152
