### ISSUE TITLE
How to deduce the maximum force generated in X, Y and Z directions for the fully-actuated UAV?

### ISSUE THREAD

**Issue by daydayupcg137** [PX4/PX4-Matrix#159]
Thank you for your [reply](https://github.com/PX4/PX4-Autopilot/issues/17164).But How to isolate fmax in the equation?There are six variables, but there are only five equations.Therefore, I cannot infer the relationship between Fmax and rpm。
the M matrix is shown below:
![image](https://user-images.githubusercontent.com/66363845/112252261-bd5ef780-8c97-11eb-8b4e-3fc7873f5c50.png)
In the above case, what is the relation of Fmax(fxmax/fymax/fzmax) with respect to the tilt Angle alpha and Beta?

I would be very grateful if you could help meThank you very much!

**Comment by daydayupcg137** [comment]
I'm sorry to bother you again. This problem has been bothering me for a long time.I don't know how to retract the relation. Right

**Comment by bresch** [comment]
I wrote this at the end of my previous reply and it is also true for this question: 
> I'm closing this post because it isn't an issue of the PX4 flight controller software. Please ask those questions on a math/physics forum.

I'm not going to answer this here.
